#!/usr/bin/env python3

import re
import sys
import pathlib

pattern = sys.argv[1] if len(sys.argv) > 1 else None

p = pathlib.Path('/Users/edsu/Projects/sul-dlss/puppet/hieradata/node/')

for node_dir in p.iterdir():
    if pattern is None or re.search(pattern, node_dir.name):
        print(node_dir.name.replace('.eyaml', ''))
