#!/usr/bin/env python3

import re
import sys
import socket

for line in sys.stdin:
    line = line.rstrip()
    match = re.search(r'(\d+\.\d+\.\d+.\d+)', line)
    if match:
        ip = match.group(1)
        try:
            host = socket.getfqdn(ip)
        except Exception as e:
            print(e)
        if type(host) == str:
            line = line.replace(ip, host)
            print(line)

