#!/usr/bin/env python3

import fileinput
import re

import requests


def lookup(s: str) -> str:
    url = f"https://en.wikipedia.org/w/api.php?action=opensearch&search={s}&limit=1&namespace=0&format=json"
    result = requests.get(url).json()
    if len(result) == 4 and len(result[3]) == 1:
        return result[3][0]
    return ""

for line in fileinput.input():
    for s in re.findall(r'\[(?!@)(.+?)\]', line):
        print(f"[{s}]: {lookup(s)}")

