#!/usr/bin/env python3

import sys

from pathlib import Path

journal = Path('/Users/edsummers/Dropbox/Journal/')

month = sys.argv[1]

hours = 0
for page in sorted(journal.iterdir()):
    date = page.name.replace('.md', '')

    if not date.startswith(month):
        continue

    text = page.open().read()
    if 'webrecorder work' not in text.lower():
        continue

    found = False
    for line in text.splitlines():
        if line.startswith('##'):
            if 'webrecorder work' in line.lower():
                found = True
            else: 
                found = False
        elif found and line.strip() != "":
            print(date, line)
            parts = line.split(":")
            hours += int(parts[-1])

print(f"Total: {hours}")

