#!/usr/bin/env python3

import sys
from pathlib import Path

if len(sys.argv) != 3:
    sys.exit('usage: work <time> <project> e.g work 2023-01 "webrecorder work"')

time = sys.argv[1]
project = sys.argv[2].lower()

journal = Path('/Users/edsummers/Dropbox/Journal/')


hours = 0
for page in sorted(journal.iterdir()):
    date = page.name.replace('.md', '')

    if not date.startswith(time):
        continue

    text = page.open().read()
    if project not in text.lower():
        continue

    found = False
    for line in text.splitlines():
        if line.startswith('##'):
            if project in line.lower():
                found = True
            else:
                found = False
        elif found and line.strip() != "":
            print(date, line)
            parts = line.split(":")
            hours += int(parts[-1])

print(f"Total: {hours}")
